services:
  frontend:
    container_name: codeflix-frontend
    build: ./codeflix-client
    ports:
      - "3000:3000"
    volumes:
      - ./codeflix-client:/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - json-server
      - graphql-server
      - keycloak
    env_file:
      - ./codeflix-client/.env
      - ./codeflix-client/.env.local
    networks:
      - codeflix-network

  json-server:
    container_name: codeflix-json-server
    image: node:20
    working_dir: /app
    volumes:
      - ./codeflix-client:/app
    ports:
      - "3333:3333"
    command: sh -c "npm install json-server@0.17.4 && npx json-server --watch db.json --host 0.0.0.0 --port 3333"
    networks:
      - codeflix-network

  graphql-server:
    container_name: codeflix-graphql-server
    build: ./codeflix-graphql-server
    ports:
      - "4000:4000"
    volumes:
      - ./codeflix-graphql-server:/app
    command: sh -c "npm install && npm run build && npm run start"
    env_file:
      - ./codeflix-graphql-server/.env
    networks:
      - codeflix-network

  postgres:
    container_name: codeflix-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codeflix-network

  keycloak:
    container_name: codeflix-keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_DATABASE: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - codeflix-network

volumes:
  postgres_data:

networks:
  codeflix-network: