import type { Metadata } from "next";
import "./globals.css";

import { LayoutClient } from "@/components/LayoutClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutClient children={children} />
      </body>
    </html>
  )
}