import type { Metadata } from "next";
import "./globals.css";

import { AnimatedBackground } from "@/components/AnimatedBackground";
import { BottomNav } from "@/components/BottomNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="theme-default">
          <AnimatedBackground />
        </div>
        <div className="relative min-h-screen">
          <main className="pb-20">{children}</main> {/* Espaço para a bottom-nav */}
          <BottomNav />
        </div>
      </body>
    </html>
  );
}